name: Workflow Evento
on:
  push:
    branches: ["main", "dev"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: echo "Action executada apenas em main e dev"
